### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by Zwilcox96** [Zwilcox96/conference-connections#1]
As a **admin** I would like to **see the home page** so that I can **access the app**

#### AC:
- [x] A webpage loads
- [x] The webpages contains some basic text and has some CSS styling

#### DOD:
- [x] All acceptance criteria are met
- [x] The feature has been tested for functionality
- [x] The feature has been tested for security

**Comment by lunarProtector** [comment]
|  ) )

**Comment by cutefeyrad** [comment]
hhh
